<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Elf.ObjectStorageAsset.SmokeTest</AssemblyName>
    <RootNamespace>Elf.ObjectStorageAsset.SmokeTest</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LiveE2E\LiveE2E.csproj" />
  </ItemGroup>

</Project>
