<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Bootstrap\Bootstrap.csproj" />
    <ProjectReference Include="..\..\src\Minio\Minio.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Elf.ObjectStorageAsset.ConsoleTest</AssemblyName>
    <RootNamespace>Elf.ObjectStorageAsset.ConsoleTest</RootNamespace>
  </PropertyGroup>

</Project>
