// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Elf.ObjectStorageAsset.Infrastructure.Persistence;

#nullable disable

namespace Elf.ObjectStorageAsset.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ObjectStorageAssetDbContext))]
    [Migration("20260306154259_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("osa")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Elf.ObjectStorageAsset.Domain.Entities.ObjectAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ETag")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("LastStatusChangedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<Guid?>("OwnerKeyGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("OwnerKeyInt64")
                        .HasColumnType("bigint");

                    b.Property<int>("OwnerKeyKind")
                        .HasColumnType("int");

                    b.Property<string>("OwnerKeyKindLabel")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasComputedColumnSql("(CASE [OwnerKeyKind] WHEN 1 THEN N'Int64' WHEN 2 THEN N'Guid' WHEN 3 THEN N'String' ELSE NULL END)", true);

                    b.Property<string>("OwnerKeyText")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("PhysicalDeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ProviderVersionId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("SizeBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<int>("SlotMultiplicity")
                        .HasColumnType("int");

                    b.Property<string>("SlotMultiplicityLabel")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasComputedColumnSql("(CASE [SlotMultiplicity] WHEN 1 THEN N'Single' WHEN 2 THEN N'Many' ELSE NULL END)", true);

                    b.Property<string>("SlotName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusLabel")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasComputedColumnSql("(CASE [Status] WHEN 1 THEN N'PendingUpload' WHEN 2 THEN N'Active' WHEN 3 THEN N'UploadFailed' WHEN 4 THEN N'PendingDelete' WHEN 5 THEN N'Deleted' WHEN 6 THEN N'DeleteFailed' ELSE NULL END)", true);

                    b.Property<string>("StorageNamespace")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("UploadedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ObjectKey")
                        .IsUnique();

                    b.HasIndex("Status", "ExpiresAtUtc");

                    b.HasIndex("OwnerType", "OwnerKeyKind", "OwnerKeyInt64", "OwnerKeyGuid", "OwnerKeyText", "SlotName")
                        .IsUnique()
                        .HasFilter("[SlotMultiplicity] = 1 AND [Status] IN (1, 2, 3, 4, 6)");

                    b.HasIndex("OwnerType", "OwnerKeyKind", "OwnerKeyInt64", "OwnerKeyGuid", "OwnerKeyText", "SlotName", "Status");

                    b.ToTable("ObjectAssets", "osa");
                });
#pragma warning restore 612, 618
        }
    }
}
