<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Helpers\Helpers.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Elf.ObjectStorageAsset.Application</PackageId>
    <Description>Abstractions and application contracts for Elf.ObjectStorageAsset.</Description>
    <AssemblyName>Elf.ObjectStorageAsset.Application</AssemblyName>
    <RootNamespace>Elf.ObjectStorageAsset.Application</RootNamespace>
  </PropertyGroup>

</Project>
